# Generated by Django 6.1 on 2026-09-13 07:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=70)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='employers')),
                ('job_title', models.CharField(max_length=70)),
                ('job_description', models.TextField()),
                ('contract_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('working_language', models.CharField(max_length=20)),
                ('job_category', models.CharField(choices=[('IT / SOftware development', 'IT / SOftware development'), ('Design / UX', 'Design / UX'), ('Marketing & Communication', 'Marketing & Communication'), ('Finance', 'Finance'), ('Operations & Support', 'Operations & Support'), ('Other', 'Other')], max_length=40)),
                ('job_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_size', models.CharField(choices=[('0-10', '0-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000')], max_length=10)),
                ('industry', models.CharField(choices=[('SaaS', 'SaaS'), ('E-commerce', 'E-commerce'), ('Technology', 'Technology'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Travel', 'Travel'), ('Food', 'Food'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Music', 'Music'), ('Arts', 'Arts'), ('Others', 'Others')], max_length=25)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate_range', models.CharField(blank=True, max_length=20, null=True)),
                ('questionnaire', models.JSONField(blank=True, default=dict, null=True)),
                ('slug', models.SlugField()),
                ('no_of_applicants', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateField(null=True)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='users')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('personality_note', models.CharField(blank=True, max_length=200, null=True)),
                ('questionnaire_answers', models.JSONField(default=dict)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=15, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobpost')),
            ],
        ),
    ]
